version: '3.7'

services:
  db:
    image: mysql
    container_name: mysql
    restart:
      'always'
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "3306:3306" # HOST:CONTAINER
