spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    url: ${DB_URL:jdbc:mysql://localhost:3306/the_commerce?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true }

    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:qwer1234}

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: ${DDL_AUTO:update}